# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_account_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(352, 228)
        Dialog.setStyleSheet("background-color: rgb(139, 83, 83);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.nameWarning = QtWidgets.QLabel(Dialog)
        self.nameWarning.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.nameWarning.setObjectName("nameWarning")
        self.verticalLayout.addWidget(self.nameWarning)
        self.passwordLabel = QtWidgets.QLabel(Dialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(Dialog)
        self.passwordEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout.addWidget(self.passwordEdit)
        self.repeatPasswordLabel = QtWidgets.QLabel(Dialog)
        self.repeatPasswordLabel.setObjectName("repeatPasswordLabel")
        self.verticalLayout.addWidget(self.repeatPasswordLabel)
        self.repeatPasswordEdit = QtWidgets.QLineEdit(Dialog)
        self.repeatPasswordEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.repeatPasswordEdit.setObjectName("repeatPasswordEdit")
        self.verticalLayout.addWidget(self.repeatPasswordEdit)
        self.passwordWarning = QtWidgets.QLabel(Dialog)
        self.passwordWarning.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.passwordWarning.setObjectName("passwordWarning")
        self.verticalLayout.addWidget(self.passwordWarning)
        self.createButton = QtWidgets.QPushButton(Dialog)
        self.createButton.setStyleSheet("background-color: rgb(137, 173, 59);")
        self.createButton.setObjectName("createButton")
        self.verticalLayout.addWidget(self.createButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nameLabel.setText(_translate("Dialog", "ФИО"))
        self.nameWarning.setText(_translate("Dialog", "Это имя уже занято"))
        self.passwordLabel.setText(_translate("Dialog", "Пароль"))
        self.repeatPasswordLabel.setText(_translate("Dialog", "Подтверждение пароля"))
        self.passwordWarning.setText(_translate("Dialog", "Пароли не совпадают"))
        self.createButton.setText(_translate("Dialog", "Создать"))
