# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\select_status_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(110, 94)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.upButton = QtWidgets.QRadioButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/up_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon)
        self.upButton.setObjectName("upButton")
        self.verticalLayout_4.addWidget(self.upButton)
        self.normalButton = QtWidgets.QRadioButton(Form)
        self.normalButton.setCheckable(True)
        self.normalButton.setObjectName("normalButton")
        self.verticalLayout_4.addWidget(self.normalButton)
        self.downButton = QtWidgets.QRadioButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon1)
        self.downButton.setObjectName("downButton")
        self.verticalLayout_4.addWidget(self.downButton)
        self.anyButton = QtWidgets.QRadioButton(Form)
        self.anyButton.setChecked(True)
        self.anyButton.setObjectName("anyButton")
        self.verticalLayout_4.addWidget(self.anyButton)
        self.verticalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.upButton.setText(_translate("Form", "Повышен"))
        self.normalButton.setText(_translate("Form", "Норма"))
        self.downButton.setText(_translate("Form", "Понижен"))
        self.anyButton.setText(_translate("Form", "Любое"))
